using OpenShipsAPI.Api.Models;

namespace OpenShipsAPI.Utility;

public static class FlagResolver
{
    private static readonly Dictionary<int, Flag> Flags = new()
    {
        [201] = new Flag { Name = "Albania", Code = "AL" },
        [202] = new Flag { Name = "Andorra", Code = "AD" },
        [203] = new Flag { Name = "Austria", Code = "AT" },
        [204] = new Flag { Name = "Portugal", Code = "PT" },
        [205] = new Flag { Name = "Belgium", Code = "BE" },
        [206] = new Flag { Name = "Belarus", Code = "BY" },
        [207] = new Flag { Name = "Bulgaria", Code = "BG" },
        [208] = new Flag { Name = "Vatican", Code = "VA" },
        [209] = new Flag { Name = "Cyprus", Code = "CY" },
        [210] = new Flag { Name = "Cyprus", Code = "CY" },
        [211] = new Flag { Name = "Germany", Code = "DE" },
        [212] = new Flag { Name = "Cyprus", Code = "CY" },
        [213] = new Flag { Name = "Georgia", Code = "GE" },
        [214] = new Flag { Name = "Moldova", Code = "MD" },
        [215] = new Flag { Name = "Malta", Code = "MT" },
        [216] = new Flag { Name = "Armenia", Code = "AM" },
        [218] = new Flag { Name = "Germany", Code = "DE" },
        [219] = new Flag { Name = "Denmark", Code = "DK" },
        [220] = new Flag { Name = "Denmark", Code = "DK" },
        [224] = new Flag { Name = "Spain", Code = "ES" },
        [225] = new Flag { Name = "Spain", Code = "ES" },
        [226] = new Flag { Name = "France", Code = "FR" },
        [227] = new Flag { Name = "France", Code = "FR" },
        [228] = new Flag { Name = "France", Code = "FR" },
        [229] = new Flag { Name = "Malta", Code = "MT" },
        [230] = new Flag { Name = "Finland", Code = "FI" },
        [231] = new Flag { Name = "Faroe Is", Code = "FO" },
        [232] = new Flag { Name = "United Kingdom", Code = "GB" },
        [233] = new Flag { Name = "United Kingdom", Code = "GB" },
        [234] = new Flag { Name = "United Kingdom", Code = "GB" },
        [235] = new Flag { Name = "United Kingdom", Code = "GB" },
        [236] = new Flag { Name = "Gibraltar", Code = "GI" },
        [237] = new Flag { Name = "Greece", Code = "GR" },
        [238] = new Flag { Name = "Croatia", Code = "HR" },
        [239] = new Flag { Name = "Greece", Code = "GR" },
        [240] = new Flag { Name = "Greece", Code = "GR" },
        [241] = new Flag { Name = "Greece", Code = "GR" },
        [242] = new Flag { Name = "Morocco", Code = "MA" },
        [243] = new Flag { Name = "Hungary", Code = "HU" },
        [244] = new Flag { Name = "Netherlands", Code = "NL" },
        [245] = new Flag { Name = "Netherlands", Code = "NL" },
        [246] = new Flag { Name = "Netherlands", Code = "NL" },
        [247] = new Flag { Name = "Italy", Code = "IT" },
        [248] = new Flag { Name = "Malta", Code = "MT" },
        [249] = new Flag { Name = "Malta", Code = "MT" },
        [250] = new Flag { Name = "Ireland", Code = "IE" },
        [251] = new Flag { Name = "Iceland", Code = "IS" },
        [252] = new Flag { Name = "Liechtenstein", Code = "LI" },
        [253] = new Flag { Name = "Luxembourg", Code = "LU" },
        [254] = new Flag { Name = "Monaco", Code = "MC" },
        [255] = new Flag { Name = "Portugal", Code = "PT" },
        [256] = new Flag { Name = "Malta", Code = "MT" },
        [257] = new Flag { Name = "Norway", Code = "NO" },
        [258] = new Flag { Name = "Norway", Code = "NO" },
        [259] = new Flag { Name = "Norway", Code = "NO" },
        [261] = new Flag { Name = "Poland", Code = "PL" },
        [262] = new Flag { Name = "Montenegro", Code = "ME" },
        [263] = new Flag { Name = "Portugal", Code = "PT" },
        [264] = new Flag { Name = "Romania", Code = "RO" },
        [265] = new Flag { Name = "Sweden", Code = "SE" },
        [266] = new Flag { Name = "Sweden", Code = "SE" },
        [267] = new Flag { Name = "Slovakia", Code = "SK" },
        [268] = new Flag { Name = "San Marino", Code = "SM" },
        [269] = new Flag { Name = "Switzerland", Code = "CH" },
        [270] = new Flag { Name = "Czech Republic", Code = "CZ" },
        [271] = new Flag { Name = "Turkey", Code = "TR" },
        [272] = new Flag { Name = "Ukraine", Code = "UA" },
        [273] = new Flag { Name = "Russia", Code = "RU" },
        [274] = new Flag { Name = "FYR Macedonia", Code = "MK" },
        [275] = new Flag { Name = "Latvia", Code = "LV" },
        [276] = new Flag { Name = "Estonia", Code = "EE" },
        [277] = new Flag { Name = "Lithuania", Code = "LT" },
        [278] = new Flag { Name = "Slovenia", Code = "SI" },
        [279] = new Flag { Name = "Serbia", Code = "RS" },
        [301] = new Flag { Name = "Anguilla", Code = "AI" },
        [303] = new Flag { Name = "USA", Code = "US" },
        [304] = new Flag { Name = "Antigua Barbuda", Code = "AG" },
        [305] = new Flag { Name = "Antigua Barbuda", Code = "AG" },
        [306] = new Flag { Name = "Curacao", Code = "CW" },
        [307] = new Flag { Name = "Aruba", Code = "AW" },
        [308] = new Flag { Name = "Bahamas", Code = "BS" },
        [309] = new Flag { Name = "Bahamas", Code = "BS" },
        [310] = new Flag { Name = "Bermuda", Code = "BM" },
        [311] = new Flag { Name = "Bahamas", Code = "BS" },
        [312] = new Flag { Name = "Belize", Code = "BZ" },
        [314] = new Flag { Name = "Barbados", Code = "BB" },
        [316] = new Flag { Name = "Canada", Code = "CA" },
        [319] = new Flag { Name = "Cayman Is", Code = "KY" },
        [321] = new Flag { Name = "Costa Rica", Code = "CR" },
        [323] = new Flag { Name = "Cuba", Code = "CU" },
        [325] = new Flag { Name = "Dominica", Code = "DM" },
        [327] = new Flag { Name = "Dominican Rep", Code = "DO" },
        [329] = new Flag { Name = "Guadeloupe", Code = "GP" },
        [330] = new Flag { Name = "Grenada", Code = "GD" },
        [331] = new Flag { Name = "Greenland", Code = "GL" },
        [332] = new Flag { Name = "Guatemala", Code = "GT" },
        [334] = new Flag { Name = "Honduras", Code = "HN" },
        [336] = new Flag { Name = "Haiti", Code = "HT" },
        [338] = new Flag { Name = "USA", Code = "US" },
        [339] = new Flag { Name = "Jamaica", Code = "JM" },
        [341] = new Flag { Name = "St Kitts Nevis", Code = "KN" },
        [343] = new Flag { Name = "St Lucia", Code = "LC" },
        [345] = new Flag { Name = "Mexico", Code = "MX" },
        [347] = new Flag { Name = "Martinique", Code = "MQ" },
        [348] = new Flag { Name = "Montserrat", Code = "MS" },
        [350] = new Flag { Name = "Nicaragua", Code = "NI" },
        [351] = new Flag { Name = "Panama", Code = "PA" },
        [352] = new Flag { Name = "Panama", Code = "PA" },
        [353] = new Flag { Name = "Panama", Code = "PA" },
        [354] = new Flag { Name = "Panama", Code = "PA" },
        [355] = new Flag { Name = "Panama", Code = "PA" },
        [356] = new Flag { Name = "Panama", Code = "PA" },
        [357] = new Flag { Name = "Panama", Code = "PA" },
        [358] = new Flag { Name = "Puerto Rico", Code = "PR" },
        [359] = new Flag { Name = "El Salvador", Code = "SV" },
        [361] = new Flag { Name = "St Pierre Miquelon", Code = "PM" },
        [362] = new Flag { Name = "Trinidad Tobago", Code = "TT" },
        [364] = new Flag { Name = "Turks Caicos Is", Code = "TC" },
        [366] = new Flag { Name = "USA", Code = "US" },
        [367] = new Flag { Name = "USA", Code = "US" },
        [368] = new Flag { Name = "USA", Code = "US" },
        [369] = new Flag { Name = "USA", Code = "US" },
        [370] = new Flag { Name = "Panama", Code = "PA" },
        [371] = new Flag { Name = "Panama", Code = "PA" },
        [372] = new Flag { Name = "Panama", Code = "PA" },
        [373] = new Flag { Name = "Panama", Code = "PA" },
        [374] = new Flag { Name = "Panama", Code = "PA" },
        [375] = new Flag { Name = "St Vincent Grenadines", Code = "VC" },
        [376] = new Flag { Name = "St Vincent Grenadines", Code = "VC" },
        [377] = new Flag { Name = "St Vincent Grenadines", Code = "VC" },
        [378] = new Flag { Name = "British Virgin Is", Code = "VG" },
        [379] = new Flag { Name = "US Virgin Is", Code = "VI" },
        [401] = new Flag { Name = "Afghanistan", Code = "AF" },
        [403] = new Flag { Name = "Saudi Arabia", Code = "SA" },
        [405] = new Flag { Name = "Bangladesh", Code = "BD" },
        [408] = new Flag { Name = "Bahrain", Code = "BH" },
        [410] = new Flag { Name = "Bhutan", Code = "BT" },
        [412] = new Flag { Name = "China", Code = "CN" },
        [413] = new Flag { Name = "China", Code = "CN" },
        [414] = new Flag { Name = "China", Code = "CN" },
        [416] = new Flag { Name = "Taiwan", Code = "TW" },
        [417] = new Flag { Name = "Sri Lanka", Code = "LK" },
        [419] = new Flag { Name = "India", Code = "IN" },
        [422] = new Flag { Name = "Iran", Code = "IR" },
        [423] = new Flag { Name = "Azerbaijan", Code = "AZ" },
        [425] = new Flag { Name = "Iraq", Code = "IQ" },
        [428] = new Flag { Name = "Israel", Code = "IL" },
        [431] = new Flag { Name = "Japan", Code = "JP" },
        [432] = new Flag { Name = "Japan", Code = "JP" },
        [434] = new Flag { Name = "Turkmenistan", Code = "TM" },
        [436] = new Flag { Name = "Kazakhstan", Code = "KZ" },
        [437] = new Flag { Name = "Uzbekistan", Code = "UZ" },
        [438] = new Flag { Name = "Jordan", Code = "JO" },
        [440] = new Flag { Name = "Korea", Code = "KR" },
        [441] = new Flag { Name = "Korea", Code = "KR" },
        [443] = new Flag { Name = "Palestine", Code = "PS" },
        [445] = new Flag { Name = "DPR Korea", Code = "KP" },
        [447] = new Flag { Name = "Kuwait", Code = "KW" },
        [450] = new Flag { Name = "Lebanon", Code = "LB" },
        [451] = new Flag { Name = "Kyrgyz Republic", Code = "KG" },
        [453] = new Flag { Name = "Macao", Code = "MO" },
        [455] = new Flag { Name = "Maldives", Code = "MV" },
        [457] = new Flag { Name = "Mongolia", Code = "MN" },
        [459] = new Flag { Name = "Nepal", Code = "NP" },
        [461] = new Flag { Name = "Oman", Code = "OM" },
        [463] = new Flag { Name = "Pakistan", Code = "PK" },
        [466] = new Flag { Name = "Qatar", Code = "QA" },
        [468] = new Flag { Name = "Syria", Code = "SY" },
        [470] = new Flag { Name = "UAE", Code = "AE" },
        [471] = new Flag { Name = "UAE", Code = "AE" },
        [472] = new Flag { Name = "Tajikistan", Code = "TJ" },
        [473] = new Flag { Name = "Yemen", Code = "YE" },
        [475] = new Flag { Name = "Yemen", Code = "YE" },
        [477] = new Flag { Name = "Hong Kong", Code = "HK" },
        [478] = new Flag { Name = "Bosnia and Herzegovina", Code = "BA" },
        [501] = new Flag { Name = "Antarctica", Code = "AQ" },
        [503] = new Flag { Name = "Australia", Code = "AU" },
        [506] = new Flag { Name = "Myanmar", Code = "MM" },
        [508] = new Flag { Name = "Brunei", Code = "BN" },
        [510] = new Flag { Name = "Micronesia", Code = "FM" },
        [511] = new Flag { Name = "Palau", Code = "PW" },
        [512] = new Flag { Name = "New Zealand", Code = "NZ" },
        [514] = new Flag { Name = "Cambodia", Code = "KH" },
        [515] = new Flag { Name = "Cambodia", Code = "KH" },
        [516] = new Flag { Name = "Christmas Is", Code = "CX" },
        [518] = new Flag { Name = "Cook Is", Code = "CK" },
        [520] = new Flag { Name = "Fiji", Code = "FJ" },
        [523] = new Flag { Name = "Cocos Is", Code = "CC" },
        [525] = new Flag { Name = "Indonesia", Code = "ID" },
        [529] = new Flag { Name = "Kiribati", Code = "KI" },
        [531] = new Flag { Name = "Laos", Code = "LA" },
        [533] = new Flag { Name = "Malaysia", Code = "MY" },
        [536] = new Flag { Name = "N Mariana Is", Code = "MP" },
        [538] = new Flag { Name = "Marshall Is", Code = "MH" },
        [540] = new Flag { Name = "New Caledonia", Code = "NC" },
        [542] = new Flag { Name = "Niue", Code = "NU" },
        [544] = new Flag { Name = "Nauru", Code = "NR" },
        [546] = new Flag { Name = "French Polynesia", Code = "PF" },
        [548] = new Flag { Name = "Philippines", Code = "PH" },
        [553] = new Flag { Name = "Papua New Guinea", Code = "PG" },
        [555] = new Flag { Name = "Pitcairn Is", Code = "PN" },
        [557] = new Flag { Name = "Solomon Is", Code = "SB" },
        [559] = new Flag { Name = "American Samoa", Code = "AS" },
        [561] = new Flag { Name = "Samoa", Code = "WS" },
        [563] = new Flag { Name = "Singapore", Code = "SG" },
        [564] = new Flag { Name = "Singapore", Code = "SG" },
        [565] = new Flag { Name = "Singapore", Code = "SG" },
        [566] = new Flag { Name = "Singapore", Code = "SG" },
        [567] = new Flag { Name = "Thailand", Code = "TH" },
        [570] = new Flag { Name = "Tonga", Code = "TO" },
        [572] = new Flag { Name = "Tuvalu", Code = "TV" },
        [574] = new Flag { Name = "Vietnam", Code = "VN" },
        [576] = new Flag { Name = "Vanuatu", Code = "VU" },
        [577] = new Flag { Name = "Vanuatu", Code = "VU" },
        [578] = new Flag { Name = "Wallis Futuna Is", Code = "WF" },
        [601] = new Flag { Name = "South Africa", Code = "ZA" },
        [603] = new Flag { Name = "Angola", Code = "AO" },
        [605] = new Flag { Name = "Algeria", Code = "DZ" },
        [607] = new Flag { Name = "St Paul Amsterdam Is", Code = "TF" },
        [608] = new Flag { Name = "Ascension Is", Code = "IO" },
        [609] = new Flag { Name = "Burundi", Code = "BI" },
        [610] = new Flag { Name = "Benin", Code = "BJ" },
        [611] = new Flag { Name = "Botswana", Code = "BW" },
        [612] = new Flag { Name = "Cen Afr Rep", Code = "CF" },
        [613] = new Flag { Name = "Cameroon", Code = "CM" },
        [615] = new Flag { Name = "Congo", Code = "CG" },
        [616] = new Flag { Name = "Comoros", Code = "KM" },
        [617] = new Flag { Name = "Cape Verde", Code = "CV" },
        [618] = new Flag { Name = "Antarctica", Code = "AQ" },
        [619] = new Flag { Name = "Ivory Coast", Code = "CI" },
        [620] = new Flag { Name = "Comoros", Code = "KM" },
        [621] = new Flag { Name = "Djibouti", Code = "DJ" },
        [622] = new Flag { Name = "Egypt", Code = "EG" },
        [624] = new Flag { Name = "Ethiopia", Code = "ET" },
        [625] = new Flag { Name = "Eritrea", Code = "ER" },
        [626] = new Flag { Name = "Gabon", Code = "GA" },
        [627] = new Flag { Name = "Ghana", Code = "GH" },
        [629] = new Flag { Name = "Gambia", Code = "GM" },
        [630] = new Flag { Name = "Guinea-Bissau", Code = "GW" },
        [631] = new Flag { Name = "Equ. Guinea", Code = "GQ" },
        [632] = new Flag { Name = "Guinea", Code = "GN" },
        [633] = new Flag { Name = "Burkina Faso", Code = "BF" },
        [634] = new Flag { Name = "Kenya", Code = "KE" },
        [635] = new Flag { Name = "Antarctica", Code = "AQ" },
        [636] = new Flag { Name = "Liberia", Code = "LR" },
        [637] = new Flag { Name = "Liberia", Code = "LR" },
        [642] = new Flag { Name = "Libya", Code = "LY" },
        [644] = new Flag { Name = "Lesotho", Code = "LS" },
        [645] = new Flag { Name = "Mauritius", Code = "MU" },
        [647] = new Flag { Name = "Madagascar", Code = "MG" },
        [649] = new Flag { Name = "Mali", Code = "ML" },
        [650] = new Flag { Name = "Mozambique", Code = "MZ" },
        [654] = new Flag { Name = "Mauritania", Code = "MR" },
        [655] = new Flag { Name = "Malawi", Code = "MW" },
        [656] = new Flag { Name = "Niger", Code = "NE" },
        [657] = new Flag { Name = "Nigeria", Code = "NG" },
        [659] = new Flag { Name = "Namibia", Code = "NA" },
        [660] = new Flag { Name = "Reunion", Code = "RE" },
        [661] = new Flag { Name = "Rwanda", Code = "RW" },
        [662] = new Flag { Name = "Sudan", Code = "SD" },
        [663] = new Flag { Name = "Senegal", Code = "SN" },
        [664] = new Flag { Name = "Seychelles", Code = "SC" },
        [665] = new Flag { Name = "St Helena", Code = "SH" },
        [666] = new Flag { Name = "Somalia", Code = "SO" },
        [667] = new Flag { Name = "Sierra Leone", Code = "SL" },
        [668] = new Flag { Name = "Sao Tome Principe", Code = "ST" },
        [669] = new Flag { Name = "Swaziland", Code = "SZ" },
        [670] = new Flag { Name = "Chad", Code = "TD" },
        [671] = new Flag { Name = "Togo", Code = "TG" },
        [672] = new Flag { Name = "Tunisia", Code = "TN" },
        [674] = new Flag { Name = "Tanzania", Code = "TZ" },
        [675] = new Flag { Name = "Uganda", Code = "UG" },
        [676] = new Flag { Name = "DR Congo", Code = "CD" },
        [677] = new Flag { Name = "Tanzania", Code = "TZ" },
        [678] = new Flag { Name = "Zambia", Code = "ZM" },
        [679] = new Flag { Name = "Zimbabwe", Code = "ZW" },
        [701] = new Flag { Name = "Argentina", Code = "AR" },
        [710] = new Flag { Name = "Brazil", Code = "BR" },
        [720] = new Flag { Name = "Bolivia", Code = "BO" },
        [725] = new Flag { Name = "Chile", Code = "CL" },
        [730] = new Flag { Name = "Colombia", Code = "CO" },
        [735] = new Flag { Name = "Ecuador", Code = "EC" },
        [740] = new Flag { Name = "UK", Code = "UK" },
        [745] = new Flag { Name = "Guiana", Code = "GF" },
        [750] = new Flag { Name = "Guyana", Code = "GY" },
        [755] = new Flag { Name = "Paraguay", Code = "PY" },
        [760] = new Flag { Name = "Peru", Code = "PE" },
        [765] = new Flag { Name = "Suriname", Code = "SR" },
        [770] = new Flag { Name = "Uruguay", Code = "UY" },
        [775] = new Flag { Name = "Venezuela", Code = "VE" },
    };

    public static Flag? GetFlag(int mmsi)
    {
        if (mmsi < 100_000_000 || mmsi > 999_999_999)
            return null;

        int prefix = mmsi / 1_000_000;

        int mid = prefix switch
        {
            11 => (mmsi / 1_000) % 1000, // 111MIDXXX
            99 => (mmsi / 10_000) % 1000, // 99MIDXXXX
            _ when prefix < 100 => (mmsi / 10_000) % 1000, // 00MIDXXXX
            _ => prefix // MIDXXXXXX
        };

        return Flags.GetValueOrDefault(mid);
    }
}